<div class="hero-unit">
  <?php

  $title = 'Add new item';
  $this->headTitle($title);
  ?>
  <h2><?php echo $this->escapeHtml($title); ?></h2>
  <?php
  $form = $this->form;
  $form->setAttribute('action', $this->url('item', array('action' => 'add')));
  $form->prepare();

  echo $this->form()->openTag($form);
  echo $this->formHidden($form->get('id'));
  echo $this->formRow($form->get('content'));
  echo $this->formSubmit($form->get('submit'));
  echo $this->form()->closeTag();
  ?>
</div>