<div class="hero-unit">
  <?php

  $title = 'Delete item';
  $this->headTitle($title);
  ?>
  <h2><?php echo $this->escapeHtml($title); ?></h2>

  <p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($item->content); ?>'?
  </p>
  <?php

  $url = $this->url('item', array(
    'action' => 'delete',
    'id'     => $this->id,
    ));
  
    ?>
    <form action="<?php echo $url; ?>" method="post">
      <div>
        <input type="hidden" name="id" value="<?php echo (int) $item->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
      </div>
    </form>
  </div>
