<div class="hero-unit">
  
  <h2>TODO</h2>
  <p>
    <a href="<?php echo $this->url('item', array('action'=>'add'));?>">Add new Todo</a>
  </p>
  <table class="table">
 
    <form name="items" action="<?php echo $this->url('item', array('action'=>'groupDelete'));?>" method="post">
    <?php foreach ($items as $item) : ?>
    <tr>
      <td><input type="checkbox" name="groupDelete[]" value="<?php echo $item->id;?>" /></td>
      <td><?php echo $this->escapeHtml($item->content);?></td>
      <td>
        <a href="<?php echo $this->url('item', array('action'=>'edit','id'=>$item->id));?>">Edit</a>
        <a href="<?php echo $this->url('item', array('action'=>'delete','id'=>$item->id));?>">Delete</a>
      </td>
    </tr>
  <?php endforeach; ?>
  <input type="submit" value="Delete selected" onclick="validate()" />
  </form>
  </table>
</div>
